/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as EliminatoriasRouteImport } from './routes/eliminatorias'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MinijuegoRouteImport } from './routes/minijuego'
import { Route as MisPronosticosRouteImport } from './routes/mis-pronosticos'
import { Route as PronosticosRouteImport } from './routes/pronosticos'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ApiPublicHooksDailySnapshotRouteImport } from './routes/api/public/hooks/daily-snapshot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const EliminatoriasRoute = EliminatoriasRouteImport.update({
  id: '/eliminatorias',
  path: '/eliminatorias',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MinijuegoRoute = MinijuegoRouteImport.update({
  id: '/minijuego',
  path: '/minijuego',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPronosticosRoute = MisPronosticosRouteImport.update({
  id: '/mis-pronosticos',
  path: '/mis-pronosticos',
  getParentRoute: () => rootRouteImport,
} as any)
const PronosticosRoute = PronosticosRouteImport.update({
  id: '/pronosticos',
  path: '/pronosticos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailySnapshotRoute =
  ApiPublicHooksDailySnapshotRouteImport.update({
    id: '/api/public/hooks/daily-snapshot',
    path: '/api/public/hooks/daily-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendario': typeof CalendarioRoute
  '/champions': typeof ChampionsRoute
  '/eliminatorias': typeof EliminatoriasRoute
  '/estadisticas': typeof EstadisticasRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/minijuego': typeof MinijuegoRoute
  '/mis-pronosticos': typeof MisPronosticosRoute
  '/pronosticos': typeof PronosticosRoute
  '/reglas': typeof ReglasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/hooks/daily-snapshot': typeof ApiPublicHooksDailySnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendario': typeof CalendarioRoute
  '/champions': typeof ChampionsRoute
  '/eliminatorias': typeof EliminatoriasRoute
  '/estadisticas': typeof EstadisticasRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/minijuego': typeof MinijuegoRoute
  '/mis-pronosticos': typeof MisPronosticosRoute
  '/pronosticos': typeof PronosticosRoute
  '/reglas': typeof ReglasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/hooks/daily-snapshot': typeof ApiPublicHooksDailySnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendario': typeof CalendarioRoute
  '/champions': typeof ChampionsRoute
  '/eliminatorias': typeof EliminatoriasRoute
  '/estadisticas': typeof EstadisticasRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/minijuego': typeof MinijuegoRoute
  '/mis-pronosticos': typeof MisPronosticosRoute
  '/pronosticos': typeof PronosticosRoute
  '/reglas': typeof ReglasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/hooks/daily-snapshot': typeof ApiPublicHooksDailySnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendario'
    | '/champions'
    | '/eliminatorias'
    | '/estadisticas'
    | '/inicio'
    | '/login'
    | '/minijuego'
    | '/mis-pronosticos'
    | '/pronosticos'
    | '/reglas'
    | '/reset-password'
    | '/api/public/hooks/daily-snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendario'
    | '/champions'
    | '/eliminatorias'
    | '/estadisticas'
    | '/inicio'
    | '/login'
    | '/minijuego'
    | '/mis-pronosticos'
    | '/pronosticos'
    | '/reglas'
    | '/reset-password'
    | '/api/public/hooks/daily-snapshot'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendario'
    | '/champions'
    | '/eliminatorias'
    | '/estadisticas'
    | '/inicio'
    | '/login'
    | '/minijuego'
    | '/mis-pronosticos'
    | '/pronosticos'
    | '/reglas'
    | '/reset-password'
    | '/api/public/hooks/daily-snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarioRoute: typeof CalendarioRoute
  ChampionsRoute: typeof ChampionsRoute
  EliminatoriasRoute: typeof EliminatoriasRoute
  EstadisticasRoute: typeof EstadisticasRoute
  InicioRoute: typeof InicioRoute
  LoginRoute: typeof LoginRoute
  MinijuegoRoute: typeof MinijuegoRoute
  MisPronosticosRoute: typeof MisPronosticosRoute
  PronosticosRoute: typeof PronosticosRoute
  ReglasRoute: typeof ReglasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksDailySnapshotRoute: typeof ApiPublicHooksDailySnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eliminatorias': {
      id: '/eliminatorias'
      path: '/eliminatorias'
      fullPath: '/eliminatorias'
      preLoaderRoute: typeof EliminatoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minijuego': {
      id: '/minijuego'
      path: '/minijuego'
      fullPath: '/minijuego'
      preLoaderRoute: typeof MinijuegoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-pronosticos': {
      id: '/mis-pronosticos'
      path: '/mis-pronosticos'
      fullPath: '/mis-pronosticos'
      preLoaderRoute: typeof MisPronosticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronosticos': {
      id: '/pronosticos'
      path: '/pronosticos'
      fullPath: '/pronosticos'
      preLoaderRoute: typeof PronosticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-snapshot': {
      id: '/api/public/hooks/daily-snapshot'
      path: '/api/public/hooks/daily-snapshot'
      fullPath: '/api/public/hooks/daily-snapshot'
      preLoaderRoute: typeof ApiPublicHooksDailySnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarioRoute: CalendarioRoute,
  ChampionsRoute: ChampionsRoute,
  EliminatoriasRoute: EliminatoriasRoute,
  EstadisticasRoute: EstadisticasRoute,
  InicioRoute: InicioRoute,
  LoginRoute: LoginRoute,
  MinijuegoRoute: MinijuegoRoute,
  MisPronosticosRoute: MisPronosticosRoute,
  PronosticosRoute: PronosticosRoute,
  ReglasRoute: ReglasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksDailySnapshotRoute: ApiPublicHooksDailySnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
